#!/bin/bash

#停止進程
killall -9 `cat config/kano``cat config/random``cat config/type`
sleep 5

#刪除文件
rm -rf *`cat config/type`
rm -rf *.new
sleep 3

#生成新文件
dd if=debug.spk |openssl des3 -d -k G9rIDmo33|tar zxf -
sleep 10


#重新生成隨機數
cat /dev/urandom | tr -dc A-Za-z0-4 | head -c 9 > config/random &
sleep 10

#重新命名文件
mv debug `cat config/kano``cat config/random``cat config/type`
sleep 5

#重新啓動進程
./start

echo 'done'
